### ISSUE TITLE
Why Arch Linux? Would this work on Raspbian?

### ISSUE THREAD

**Issue by RichusX** [husam212/WiFighter#2]

**Comment by husam212** [comment]
It should work but since there is no mdk3 package in Raspbian repository you have to (1) download the source for mdk3 and compile it. (2) configure sysvinit to make wifighter.py run automatically after boot.

**Comment by RichusX** [comment]
Ok, thanks. Only asking because pacman didn't find mdk3 and other packages.

**Comment by husam212** [comment]
mdk3 is available in AUR, you can install it with yaourt or packer.
